version: '2.2'

services:
  jenkins:
    image: jenkins/jenkins
    networks:
      lan:
        ipv4_address: 172.1.1.10

  sonarqube:
    image: owasp/sonarqube
    networks:
      lan:
        ipv4_address: 172.1.1.20

networks:
  lan:
    ipam:
      config:
        - subnet: 172.1.1.0/24